### ISSUE TITLE
FunKiiU Suddenly Stops Working

### ISSUE THREAD

**Issue by amayra** [llakssz/FunKiiU#44]
FunKiiU stop downloading and freezing in the same percentage until i restart to resume i can't keep downloading same file without keep my eyes in FunKiiU and restart every 3 or 5 min

**Comment by amayra** [comment]
this error log :

Traceback (most recent call last):
  File "J:\cemu\FunKiiU.py", line 451, in <module>
    tickets_only=arguments.tickets_only)
  File "J:\cemu\FunKiiU.py", line 409, in main
    process_title_id(title_id, title_key, name, region, output_dir, retry_count, onlinetickets, patch_demo, patch_dlc, simulate, tickets_only)
  File "J:\cemu\FunKiiU.py", line 321, in process_title_id
    if not download_file('{}/{}.h3'.format(baseurl, c_id), outfnameh3, retry_count, ignore_404=True):
  File "J:\cemu\FunKiiU.py", line 109, in download_file
    infile = urlopen(url)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1121, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

J:\cemu>pause
Press any key to continue . . .

**Comment by V10lator** [comment]
The problem is:

An existing connection was forcibly closed by the remote host

Try https://pastebin.com/5tNswBAX - note that it will freeze untill the network connection times out but then it will resume the download.
